Update deps to make it work on Node 18
dichovsky/pdf-to-png-converter pull request #22
Opened 2022-11-04 12:40 UTC by EHadoux

This PR fixes #20.
node-canvas has been released with pre-built binaries for Node 18, which was the last bit left to make it runnable on all platforms.

2022-11-07 13:55 UTC, sternam requested changes
@dichovsky @EHadoux This looks good to me, just one minor comment is my suggested changes: it is preferable to pin non-dev dependencies to specific versions.

2022-11-07 13:55 UTC, sternam commented on package.json
> +    "canvas": ">=2.10.2",
```suggestion
    "canvas": "2.10.2",
```

2022-11-07 13:55 UTC, sternam commented on package.json
> +    "pdfjs-dist": "^3.0.0"
```suggestion
    "pdfjs-dist": "3.0.0"
```

2022-11-09 16:55 UTC, EHadoux commented
Hey, all done, although I don't think it's preferable at all. Not pinning canvas would have removed the need for this PR. Now we have `overrides` in package.json so it's fine, but we don't benefit from the tests of this repo.

2022-11-09 17:49 UTC, sternam approved these changes
@dichovsky Could you please merge or give write ability to me or @EHadoux ?  This is holding up my migration to Node v18

> Hey, all done, although I don't think it's preferable at all. Not pinning canvas would have removed the need for this PR. Now we have `overrides` in package.json so it's fine, but we don't benefit from the tests of this repo.

💯 Thanks @EHadoux!  I think it is best practice what you're doing now: to pin to specific version for `dependencies` but use the `^` in devDependencies.

2022-11-21 21:45 UTC, merged